schemaVersion: "0.3"
description: |-
  # 自動開閉局Automation Runbook
  1. Systems Manager Change Calender の状態を取得
  1. OPEN の場合は開局を実施
  1. CLOSED の場合は閉局を実施
parameters:
  InstanceId:
    type: String
    description: Target Instance Id
  ListenerRuleArn:
    type: String
    description: ListenerRuleArn
  TargetGroupArn:
    type: String
    description: TargetGroup Arn
  AssumeRoleArn:
    type: String
    description: SSM Automation Assume Role Arn
  ChangeCalenderName:
    type: String
    description: Change Calender Name
  NotificationConfigurationArn:
    type: String
    description: Target Notification Configuration
  ChannelArn:
    type: String
    description: Target Delivery Channel
assumeRole: "{{ AssumeRoleArn }}"
mainSteps:
  - name: GetCalendarState
    action: aws:executeAwsApi
    nextStep: Open_or_Close
    isEnd: false
    inputs:
      Service: ssm
      Api: GetCalendarState
      CalendarNames:
        - "{{ ChangeCalenderName }}"
    outputs:
      - Type: String
        Name: CurrentState
        Selector: $.State
  - name: Open_or_Close
    action: aws:branch
    isEnd: true
    inputs:
      Choices:
        - NextStep: StartInstances
          Variable: "{{ GetCalendarState.CurrentState }}"
          StringEquals: OPEN
        - NextStep: DisassociateAunChannel
          Variable: "{{ GetCalendarState.CurrentState }}"
          StringEquals: CLOSED
  - name: DisassociateAunChannel
    action: aws:executeScript
    nextStep: SetRulePriorities_1
    isEnd: false
    inputs:
      Runtime: python3.11
      Handler: disassociate_channel
      Script: |-
        def disassociate_channel(events, context):
          import boto3
          aun = boto3.client('notifications', region_name="us-east-1")

          try:
            # Disassociate channel
            aun.disassociate_channel(
                notificationConfigurationArn=events['ConfArn'],
                arn=events['ChannelArn']
            )

            return {
                "status": "success",
                "message": "Channel disassociated"
            }

          except Exception as e:
            return {
                "status": "error",
                "message": str(e)
            }
      InputPayload:
        ConfArn: "{{ NotificationConfigurationArn }}"
        ChannelArn: "{{ ChannelArn }}"
  - name: StartInstances
    action: aws:executeAwsApi
    nextStep: WaitRunningInstance
    isEnd: false
    inputs:
      Service: ec2
      Api: StartInstances
      InstanceIds:
        - "{{ InstanceId }}"
  - name: WaitRunningInstance
    action: aws:waitForAwsResourceProperty
    nextStep: WaitTargetGroupHealth
    isEnd: false
    inputs:
      Service: ec2
      Api: DescribeInstanceStatus
      PropertySelector: $.InstanceStatuses[0].InstanceState.Name
      DesiredValues:
        - running
      InstanceIds:
        - "{{ InstanceId }}"
      IncludeAllInstances: true
  - name: WaitTargetGroupHealth
    action: aws:waitForAwsResourceProperty
    nextStep: SetRulePriorities_100
    isEnd: false
    inputs:
      Service: elbv2
      Api: DescribeTargetHealth
      PropertySelector: $.TargetHealthDescriptions[0].TargetHealth.State
      DesiredValues:
        - healthy
      Targets:
        - Id: "{{ InstanceId }}"
      TargetGroupArn: "{{ TargetGroupArn }}"
  - name: SetRulePriorities_100
    action: aws:executeAwsApi
    nextStep: AssociateAunChannel
    isEnd: false
    inputs:
      Service: elbv2
      Api: SetRulePriorities
      RulePriorities:
        - Priority: 100
          RuleArn: "{{ ListenerRuleArn }}"
  - name: AssociateAunChannel
    action: aws:executeScript
    isEnd: true
    inputs:
      Runtime: python3.11
      Handler: associate_channel
      Script: |-
        def associate_channel(events, context):
          import boto3
          aun = boto3.client('notifications', region_name="us-east-1")

          try:
            # Associate channel
            aun.associate_channel(
                notificationConfigurationArn=events['ConfArn'],
                arn=events['ChannelArn']
            )

            return {
                "status": "success",
                "message": "Channel associated"
            }

          except Exception as e:
            return {
                "status": "error",
                "message": str(e)
            }
      InputPayload:
        ConfArn: "{{ NotificationConfigurationArn }}"
        ChannelArn: "{{ ChannelArn }}"
  - name: SetRulePriorities_1
    action: aws:executeAwsApi
    nextStep: StopInstances
    isEnd: false
    inputs:
      Service: elbv2
      Api: SetRulePriorities
      RulePriorities:
        - Priority: 1
          RuleArn: "{{ ListenerRuleArn }}"
  - name: StopInstances
    action: aws:executeAwsApi
    nextStep: WaitStoppedInstance
    isEnd: false
    inputs:
      Service: ec2
      Api: StopInstances
      InstanceIds:
        - "{{ InstanceId }}"
  - name: WaitStoppedInstance
    action: aws:waitForAwsResourceProperty
    isEnd: true
    inputs:
      Service: ec2
      Api: DescribeInstanceStatus
      PropertySelector: $.InstanceStatuses[0].InstanceState.Name
      DesiredValues:
        - stopped
      InstanceIds:
        - "{{ InstanceId }}"
      IncludeAllInstances: true
